# Generated by Django 5.1.1 on 2024-09-14 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FornitureModel3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file_url', models.URLField()),
                ('forniture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='productos.furnituremodel')),
            ],
        ),
        migrations.CreateModel(
            name='FornitureImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('color_variant', models.CharField(blank=True, max_length=50, null=True)),
                ('forniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='productos.furnituremodel')),
            ],
        ),
    ]
