# Generated by Django 5.1.1 on 2024-09-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_furnituremodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituremodel',
            name='images',
        ),
    ]
