# Generated by Django 5.1.1 on 2024-09-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_rename_forniture_fornituremodel3dmodel_furniture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitureimagemodel',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fornituremodel3dmodel',
            name='model_file_url',
            field=models.URLField(max_length=500),
        ),
    ]
