# Generated by Django 5.1.1 on 2024-09-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_fornitureimagemodel_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituremodel',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
